### ISSUE TITLE
Grench lein broken?

### ISSUE THREAD

**Issue by arichiardi** [technomancy/grenchman#34] opened 2015-11-05 02:37 UTC
I get an error when I launch, for instance `grench lein help`. The conf below, this is the error I get:

```
Exception in thread "nREPL-worker-0" java.lang.Error: java.net.SocketException: Socket closed
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at clojure.tools.nrepl.transport$bencode$fn__243.invoke(transport.clj:103)
    at clojure.tools.nrepl.transport.FnTransport.send(transport.clj:28)
    at clojure.tools.nrepl.middleware.render_values$wrap_renderer$reify__1138.send(render_values.clj:30)
    at cider.nrepl.middleware.track_state$make_transport$reify__15743.send(track_state.clj:186)
    at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__679$fn__682.invoke(interruptible_eval.clj:223)
    at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__674.invoke(interruptible_eval.clj:190)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    ... 2 more
```

It looks like a nrepl middleware issue. If I remove my `profile.clj` the error changes in:

```
Unknown status: 19:namespace-not-found
```

Can I do something to debug?

My conf:

```
Leiningen 2.5.3 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM
nREPL server started on port 34379 on host 127.0.0.1 - nrepl://127.0.0.1:34379
REPL-y 0.3.7, nREPL 0.2.11
Clojure 1.7.0
```

**Comment by technomancy** [comment] 2015-11-05 04:19
Are you trying to connect to a `lein repl` instance that is running outside a project? Connecting to a project repl won't work.

**Comment by arichiardi** [comment] 2015-11-05 04:42
Yep, very weird

**Comment by arichiardi** [comment] 2015-11-06 01:22
Anything to debug the issue?

**Comment by technomancy** [comment] 2015-11-06 02:44
The only thing I can think of is trying to move your user profiles out of the way and see if that makes a difference.

**Comment by arichiardi** [comment] 2015-11-06 02:47
Mmm this is exactly what I have written in the issue, the message changes to Unknown namespace. Sorry for the type btw. Can you give me a working conf? Maybe I have too many up-to-date things.
Thanks for you help.

**Comment by technomancy** [comment] 2015-11-06 03:02
I see; I misread the original. The only namespaces that the `lein` subtask uses are `leiningen.core.eval` and `leiningen.core.main`, so if these namespaces are not found it means that it's connecting to an nREPL server which does not have Leiningen loaded in it.

An empty `profiles.clj` is a working config on my setup, provided the nREPL server is launched correctly.

**Comment by arichiardi** [comment] 2015-11-06 03:03
With lein 2.5.3?

**Comment by technomancy** [comment] 2015-12-13 14:15
I tried this again with lein 2.5.2 and I can reproduce the problem. It works fine on 2.5.1. I haven't been tracking the changes since 2.5.1, but I believe a new nrepl version was introduced which probably caused this problem. I would recommend getting nrepl to emit a more descriptive error message so you can tell *which* namespace it is that cannot be found.

**Comment by JacksonGariety** [comment] 2016-04-06 09:11
Any status on this? How can I get around this bug?

**Comment by technomancy** [comment] 2016-04-06 09:46
Sorry, not sure what changes in nrepl caused this. I'm not using Leiningen or Grenchman these days.

**Comment by arichiardi** [comment] 2016-04-06 16:38
I confirm the problem still happens with error:
```Unknown status: 19:namespace-not-found```

**Comment by JacksonGariety** [comment] 2016-04-06 17:01
@technomancy what are you using?

**Comment by technomancy** [comment] 2016-04-07 02:33
@coleman I'm semi-retired from developing, but I have some projects going on in Racket and I hack on a game in Lua in my free time. I don't really write any server-side code these days, so not a lot of call for Clojure.

**Comment by hyPiRion** [comment] 2016-04-07 09:22
@JacksonGariety If there's interest, I can attempt to revive this project.

**Comment by JacksonGariety** [comment] 2016-04-07 16:16
@hyPiRion I'm more curious what people do in leu of it. Drip doesn't seem to make any difference in start-time to me.

**Comment by arichiardi** [comment] 2016-04-07 17:30
@JacksonGariety thanks for bringing this up, I would be interested as well.

**Comment by technomancy** [comment] 2017-03-21 17:54
This is actually due to a bug in Leiningen where it has started spinning up project JVMs every time you start a repl, not just when you start a repl inside a project: https://github.com/technomancy/leiningen/commit/6234419b#commitcomment-21422061

It should be fixed in the next release of Leiningen; in the mean time you will need to start your repl server inside a project that has `:eval-in :leiningen` (like Leiningen itself) instead of outside a project dir.

**Closed by technomancy** 2017-03-21 17:54 UTC
